### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by daveloyall** [bradleypallen/doomsday#1]
Hello!  "It didn't work."  Here's the error message:

    hobbes@magic:~/src/doomsday$ ./doomsday.py 
    Type 'q' to quit, 0 - 6 to enter the day of the week.
    February 13th, 2558? 0   
    Traceback (most recent call last):
      File "./doomsday.py", line 214, in <module>
        main()
      File "./doomsday.py", line 198, in main
        elif input_dow.isdigit():
    AttributeError: 'int' object has no attribute 'isdigit'

Maybe I'm not using the right python or something?

`doomsday.py` has a `#!/usr/bin/env python` at the top, so let's check what that ends up with...

    hobbes@magic:~/src/doomsday$ /usr/bin/env python --version
    Python 2.7.11

**Comment by daveloyall** [comment]
Confirmed, if I change `#!/usr/bin/env python` to `#!/usr/bin/env python3`, it works as expected.

**Comment by bradleypallen** [comment]
Sorry, it only took me 3+ years to notice this issue. Refactoring now to make it a package and a bit more Python3ic.
